### ISSUE TITLE
El uso de listas

### ISSUE THREAD

**Issue by Pri-PJ** [obj1-unahur-2023s1/presentacion-personal-SantinoGaldin1#1]
A tu presentación le faltaría agregar alguna de las dos listas.
Una lista ordenada se realiza agregando por ejemplo:
1.
2.
etc
o una lista desordenada se haría con -

**Comment by SantinoGaldin1** [comment]
Tendrias que esperar a que el proyecto este finalizado antes de comentar,gracias igual por tu conocimiento basico.

**Comment by Pri-PJ** [comment]
solo era una critica constructiva 😔 y para fines educativos, que pena la reacción agresiva 😔
